# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm build
  displayName: 'Build App'

- script: |
    CI=true npm run test
  displayName: 'Run tests'
  condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"

- script: |
    git config --global user.email $(EMAIL)
    git config --global user.name  $(NAME)
  displayName: "Config git credentials"
  condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"


- script: |
    node deploy.js $(USERNAME) $(ACCESS_TOKEN)
  displayName: 'Deploy App to GitHub Pages'
  condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
